### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by jwyg** [openspending/community.openspending.org#12]
I'd also change this from /resources/osi to something reflecting the content rather than the funder if possible, e.g. /resources/mappingcommunity or suchlike

**Comment by lucychambers** [comment]
Tryggvi - would it be possible for you to handle?

**Comment by trickvi** [comment]
@lucychambers I agree with @jwyg. Do you know if this will break any links somewhere, i.e. has this URL been shown to anyone outside OpenSpending (and possibly linked)? It might also be something @nmashton is interested in because he's been moving stuff from dotorg to WordPress and this is probably something that's included in the move.
